server:
  servlet:
    context-path: /
  tomcat:
    # https 에서 http로 redirect 되게 하지 않게 설정
    use-relative-redirects: true

spring:
  application:
    name: brunoviewer
  # thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*

# logging
logging:
  level:
    moka.brunoviewer: info